# Generated by Django 5.1.1 on 2024-09-20 02:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0002_account_id_alter_account_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="user",
            new_name="account",
        ),
    ]
